In [1]:
# Dependencies

%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# Multi-Linear Regression

### Multiple Linear Regression just means that you have multiple features (X) to consider

For Example:  

Y = Bias + X*Feature1 + X*Feature2 + X*Feature3 ...

More commonly written as:

<img src="images/multilinear regression formula.png">

In [3]:
# The only difference is that now you have multiple X's (features) to train

from sklearn.datasets import make_regression

n_features = 3
X, y = make_regression(n_samples=30, n_features=n_features, n_informative=n_features, 
                      random_state=42, noise=0.5, bias=100.0)

#NOTE: n_informative is saying that all features (3) have an impact on the output.

print(X.shape)
print(y.shape)
print(X)
print(y)

(30, 3)
(30,)
[[ 1.56464366 -2.6197451  -0.03582604]
 [-1.4123037   1.46564877 -0.90802408]
 [ 1.47789404 -0.51827022  0.35711257]
 [-0.3011037  -1.47852199 -0.11564828]
 [ 0.73846658  0.17136828  0.19686124]
 [ 0.0675282  -1.42474819 -0.2257763 ]
 [-0.18565898 -1.10633497 -0.47917424]
 [-1.95967012 -1.32818605  0.2088636 ]
 [-0.60063869 -0.29169375  0.37569802]
 [-0.50175704  0.91540212 -0.8084936 ]
 [ 0.76743473 -0.46947439  1.57921282]
 [ 0.81252582  1.35624003 -1.19620662]
 [ 0.93128012 -0.83921752  1.03099952]
 [ 0.82254491 -1.22084365 -1.05771093]
 [ 0.11092259 -1.15099358 -0.54438272]
 [-0.1382643   0.64768854  0.49671415]
 [-0.676922    0.61167629 -0.38508228]
 [-0.46063877  1.05712223 -0.71984421]
 [-1.98756891 -0.21967189  0.09176078]
 [ 0.08704707 -0.29900735  0.8219025 ]
 [-0.23415337 -0.23413696  1.52302986]
 [ 0.33126343  0.97554513 -0.30921238]
 [-1.91328024 -1.72491783  0.24196227]
 [-1.01283112  0.31424733 -0.56228753]
 [-1.76304016  0.32408397  0.34361829]
 [ 0.361395

#### Plotting a 3 dimensional plot using 3 features is hard for a human to comprehend. Things get more complicated as we code it out, but luckily we can just supply our n_dimensional features and sklearn will fit the model using all of our features.

In [4]:
# Linear Regression dependencies
from sklearn.linear_model import LinearRegression

In [6]:
# Step 1: Fit (train) the model for all features (X)
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [7]:
score = model.score(X, y)
print("R Squared Score: {}".format(score))

R Squared Score: 0.9999838079561164
