# First Neural Network (Keras)

In [5]:
# Step 1: Import the Data

from sklearn.datasets import make_classification

In [6]:
# Step 2: assign your X and y variables

X, y = make_classification(n_features=3, n_redundant=0, n_informative=3, random_state=42, n_classes=2,
                          n_clusters_per_class=1)

# Reshape the y to make a 2dimensional array
y = y.reshape(-1, 1)

In [7]:
print(X[:5])
print(y[:5])

[[-0.86958066 -0.87701464  0.442002  ]
 [-2.1527845  -0.37230103 -0.64729718]
 [-2.11161929 -0.48086296 -0.51786597]
 [ 1.12660111 -2.70423633  2.8518044 ]
 [-1.56110675 -0.87568159  0.30653508]]
[[0]
 [0]
 [0]
 [1]
 [0]]


In [8]:
# Step 3: Train test split to make the datasets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

These datasets would need to be scaled

In [9]:
# Step 4: preprocessing the data to scale it, then fit the data

from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [10]:
# Step 5: Scale both the training and testing data

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_train)

In [11]:
# Step 6: Use one-hot encoding to encode the labels (y)

from keras.utils import to_categorical

# One Hot Encoding
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)
print(y_train_categorical[:5])

[[0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


### The Neural Network: Creating the Model

* Step 1: Decide on the model you want to build for the data
    * Numerical Data --> use a REGRESSOR MODEL
    * Categorical Data --> use a CLASSIFIER MODEL

Because this dataset was made using "make_classification" it is transparently a categorical dataset. Use CLASSIFIER MODEL

In [13]:
# Step 2: Define the model architecture (i.e. the layers)

from keras.models import Sequential

model = Sequential()

In [ ]:
# Step 3: add in the input layer. Here you define the number of inputs (first layer), and
# the number of nodes in the hidden layer (second++ layer, the layer that receives input layer)

from keras.layers import Dense
number_of_inputs = 3
number_of_hidden_nodes = 4
model.add(Dense(units=number_of_hidden_nodes, activation='relu', input_dim=number_of_inputs))